### ISSUE TITLE
헤더 부분의 네비게이터 탭 제작

### ISSUE THREAD

**Issue by gofla1996** [OASIS-YOP/23-summer-YOP#10]
## IssueName
> 헤더 부분의 네비게이터 탭 UI 수정 및 제작

## Description
> ![image](https://github.com/OASIS-YOP/23-summer-YOP/assets/127684309/d194e4d4-5935-43d4-a2ae-4c151ef32c77)

## Todo
- [x] 누르면 창 바뀌는 탭 컴포넌트 만들기
- [x] 네비게이터 탭 버튼 UI 수정 1. 아이콘 추가
- [x] 네비게이터 탭 버튼 UI 수정 2. 눌렀을 때 높이 색깔 변화 등
- [x] 헤더 배경 그라디언트 효과
