### ISSUE TITLE
스타일드 컴포넌트

### ISSUE THREAD

**Issue by gofla1996** [OASIS-YOP/23-summer-YOP#18]
## IssueName
> CSS를 스타일드 컴포넌트로 변경

## Description
> ![image](https://github.com/OASIS-YOP/23-summer-YOP/assets/127684309/42e70c8e-9387-4238-8461-d50c9477ca44)
사진 속 NavigatorBar의 css를 스타일드 컴포넌트 방식으로 수정
## Todo
- [x] 스타일드 컴포넌트로 치환
- [x] CSS 파일 삭제
- [x] NavigatorBar -> NavigationBar로 이름 통일
