### ISSUE TITLE
텍스트 탭 기능 구현

### ISSUE THREAD

**Issue by urimJ** [OASIS-YOP/23-summer-YOP#28]
## IssueName
> 텍스트 탭 기능 구현

## Description
> 텍스트 탭의 세부 기능을 구현합니다.

## Todo
- [x] 텍스트 버튼 만들기
- [x] 텍스트 배경색 추가 버튼 넣기
- [x] 텍스트 폰트 변경

**Comment by urimJ** [comment]
import './fonts/font.css';
