### ISSUE TITLE
스티커/프레임 기능 제작

### ISSUE THREAD

**Issue by gofla1996** [OASIS-YOP/23-summer-YOP#35]
## IssueName
> 스티커와 프레임 기능 제작
## Description
> 위와 같음

## Todo
- [x] 툴박스 탭 토글 기능 구현(누르면 컨텐츠 바뀌는)
- [x] 스티커 박스 세로 스크롤 기능 추가
- [x] 스티커를 눌렀을 때 캔버스에 스티커 추가되는 기능 제작
- [x] 캔버스에 추가된 스티커를 이동 회전 크기 조절 등 가능하게 하기
- [x] 프레임 스티커 뒤로 가게 만들기
- [x] 캔버스 요소들 앞으로/뒤로 가게 만드는 버튼 기능 구현
- [x] 캔버스에 추가된 스티커 지우기, 복제 기능 추가(컨텍스트 박스)
- [x] 캔버스 사이즈에 맞는 프레임 목록 불러오기 기능 제작
- [x] 프레임 오른쪽으로 치우친 거 조정하기

**Comment by mintnaka** [comment]
8월 9일~ 
작업 목록입니다!

- [x]  캔버스 요소들 앞으로/뒤로 가게 만드는 버튼 기능 구현
- [x]  캔버스에 추가된 스티커 지우기, 복제 기능 추가(컨텍스트 박스)
- [x]  캔버스 사이즈에 맞는 프레임 목록 불러오기 기능 제작
- [x]  프레임 오른쪽으로 치우친 거 조정하기
