### ISSUE TITLE
~8/15 분배

### ISSUE THREAD

**Issue by sooje0ng** [OASIS-YOP/23-summer-YOP#48]
## IssueName
> 8월 15일까지 완성하기로 한 기능들입니다.

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [x] 이미지 tab - filters: 명도, 채도, 대비 구현하기
- [x] 이미지 불러온 상태에서 또 불러오기 할 때 새 이미지로 대체되지 않는 버그 해결
- [x] 자르기 대체 기능 구현하기
- [ ] 요소를 선택하면 delete가 자체 생성되게 구현하기 (기획에서 삭제됨. 보류)

**Comment by mintnaka** [comment]
수정님! 명도, 채도, 대비 조절하는 거 양수로만 조절 가능한 게 아니라 음수로도 조절 가능하게 만드는 건 불가능할까요?? 지금은 전부 값을 올리는 것만 가능한 것 같아서요!

**Comment by sooje0ng** [comment]
> 수정님! 명도, 채도, 대비 조절하는 거 양수로만 조절 가능한 게 아니라 음수로도 조절 가능하게 만드는 건 불가능할까요?? 지금은 전부 값을 올리는 것만 가능한 것 같아서요!

네넵 확인 후 수정했습니다! 나중에 풀리퀘하겠습니다!
