### ISSUE TITLE
~8/21

### ISSUE THREAD

**Issue by sooje0ng** [OASIS-YOP/23-summer-YOP#58]
## IssueName
>  8월21일까지 완성하기로 한 기능들입니다.

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [x] imageTab ang,size - 중앙이 기준되도록 수정 시도(가능하다면)
- [x] 이미지 없을 시 range input, button 모두 비활성화
- [x] range input 색 바꾸기
- [x] 초기화면- 아무것도 선택하지 않았을 때 확인눌러도 넘어가지는거 방지.
- [x] 명도채도대비 범위 넓히기, 중앙값 0으로 ui수정
- [x] 초기화면으로 가는 아이콘 추가(headnavContainer에)
- [x] icon 반영(hover기능 추가)
- [ ] 캔버스size 반응형으로 수정
- [ ] canvas 컴퓨터에 저장
- [ ] backend와 연동하는 formdata 구상
