### ISSUE TITLE
8월 21까지 진행할 것들(혜림)

### ISSUE THREAD

**Issue by mintnaka** [OASIS-YOP/23-summer-YOP#63]
## IssueName
> 8월 21일 마감

## Description
> 8월 17일 회의 이후 할 일들

## Todo
- [x] 스티커 프레임 샘플 가져오기/그리기
- [x] 좌측 버튼 아이콘 제작
- [x] UI 다듬기
- [ ] Ctr + c/v/z/x/a 등 키 이벤트 제작
- [x] 프레임 삭제 기능
- [x] 스티커 그룹화 해서 종류별 sort 하기(사이즈 설정)
- [x] 온폴 로고 제작
- [ ] 시간되면 프레임 누끼 깔끔한 버전으로 제작
