### ISSUE TITLE
~8/23

### ISSUE THREAD

**Issue by sooje0ng** [OASIS-YOP/23-summer-YOP#70]
## IssueName
> ~8/23

## Description
> 8/23까지 맡은 기능들입니다.

## Todo
- [x] 툴팁 버그 수정
- [x] 모두지우기 클릭 시 confirm message
- [x] 사이즈 선택페이지아이콘 옮기기
- [x] TabMenuContainer UI
- [x] 이미지 불러올 때마다 range값 초기화
- [x] 저장기능 구현
